# Generated by Django 5.2.3 on 2025-06-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_slug_alter_blogpost_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, db_default='BlogPost', unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
