# Generated by Django 5.2.3 on 2025-06-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('socialLink', models.URLField(blank=True, help_text='Connect your social accounts')),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
